@startuml Manage Booked (DELETE)

header Sameple Dentist Booking Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Booked (DELETE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:booked" as routerBooked
participant "<<controllers>>\n:booked" as controllersBooked
participant "<<model>>\n:booked" as modelBooked
database "<<MongoDB>>\n:booked" as BookedDatabase


client->server: req.put('/booked/:id')
server->routerBooked: app.use('/booked/:id',booked)
routerBooked -> controllersBooked: deleteBookingByAdmin()
activate controllersBooked
controllersBooked->modelBooked: findById(req.params.id);
modelBooked ->BookedDatabase ++: BookedSchema
BookedDatabase --> modelBooked --: booked
modelBooked-->controllersBooked: existingBooking
alt   existingBooking.length !== 0
    controllersBooked->modelBooked: deleteOne()
    modelBooked ->BookedDatabase ++: BookedSchema
    BookedDatabase --> modelBooked --: booked
    modelBooked-->controllersBooked: booked
end

controllersBooked->client: response

@enduml